version: '2'
services:
  web:
      build: ./nginx
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./blog:/blog
          - ${LETS_ENCRYPT_DIR}:/etc/letsencrypt
          - ./site.conf:/etc/nginx/conf.d/site.conf
      links:
          - php
          - yofloco
          - drone-server
  php:
      image: php:7-fpm
      volumes:
          - ./blog:/blog

  yofloco:
      image: aledlewis/yofloco:latest


  drone-server:
          image: drone/drone:0.8
          volumes:
                  - /var/lib/drone:/var/lib/drone/
          restart: always
          environment:
                  - DRONE_OPEN=true
                  - DRONE_HOST=${DRONE_HOST}
                  - DRONE_BITBUCKET=true
                  - DRONE_BITBUCKET_CLIENT=${DRONE_BITBUCKET_CLIENT}
                  - DRONE_BITBUCKET_SECRET=${DRONE_BITBUCKET_SECRET}
                  - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
          image: drone/agent:0.8

          command: agent
          restart: always
          depends_on:
                  - drone-server
          volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
          environment:
                  - DRONE_SERVER=drone-server:9000
                  - DRONE_SECRET=${DRONE_SECRET}

